/*
* generated by Xtext
*/
package com.holycityaudio.spincadmenu.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.holycityaudio.spincadmenu.services.SpinCADMenuGrammarAccess;

public class SpinCADMenuParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SpinCADMenuGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.holycityaudio.spincadmenu.parser.antlr.internal.InternalSpinCADMenuParser createParser(XtextTokenStream stream) {
		return new com.holycityaudio.spincadmenu.parser.antlr.internal.InternalSpinCADMenuParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Menu";
	}
	
	public SpinCADMenuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpinCADMenuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
