/*
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSpinCADMenuValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.holycityaudio.spincadmenu.spinCADMenu.SpinCADMenuPackage.eINSTANCE);
		return result;
	}
}
