/*
 * generated by Xtext
 */
package com.holycityaudio.spincad.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSpinCADValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.holycityaudio.spincad.spinCAD.SpinCADPackage.eINSTANCE);
		return result;
	}
}
