/*
* generated by Xtext
*/
package com.holycityaudio.spincadmenu.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.holycityaudio.spincadmenu.services.SpinCADMenuGrammarAccess;

public class SpinCADMenuParser extends AbstractContentAssistParser {
	
	@Inject
	private SpinCADMenuGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.holycityaudio.spincadmenu.ui.contentassist.antlr.internal.InternalSpinCADMenuParser createParser() {
		com.holycityaudio.spincadmenu.ui.contentassist.antlr.internal.InternalSpinCADMenuParser result = new com.holycityaudio.spincadmenu.ui.contentassist.antlr.internal.InternalSpinCADMenuParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
					put(grammarAccess.getMENU_HEADERAccess().getGroup(), "rule__MENU_HEADER__Group__0");
					put(grammarAccess.getMENU_ITEMAccess().getGroup(), "rule__MENU_ITEM__Group__0");
					put(grammarAccess.getTEST_ITEMAccess().getGroup(), "rule__TEST_ITEM__Group__0");
					put(grammarAccess.getMenuAccess().getElementsAssignment(), "rule__Menu__ElementsAssignment");
					put(grammarAccess.getMENU_HEADERAccess().getNameAssignment_1(), "rule__MENU_HEADER__NameAssignment_1");
					put(grammarAccess.getMENU_ITEMAccess().getNameAssignment_1(), "rule__MENU_ITEM__NameAssignment_1");
					put(grammarAccess.getMENU_ITEMAccess().getClassNameAssignment_2(), "rule__MENU_ITEM__ClassNameAssignment_2");
					put(grammarAccess.getTEST_ITEMAccess().getClassNameAssignment_1(), "rule__TEST_ITEM__ClassNameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.holycityaudio.spincadmenu.ui.contentassist.antlr.internal.InternalSpinCADMenuParser typedParser = (com.holycityaudio.spincadmenu.ui.contentassist.antlr.internal.InternalSpinCADMenuParser) parser;
			typedParser.entryRuleMenu();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SpinCADMenuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SpinCADMenuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
