/**
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu.ui.contentassist;

import com.holycityaudio.spincadmenu.ui.contentassist.AbstractSpinCADMenuProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SpinCADMenuProposalProvider extends AbstractSpinCADMenuProposalProvider {
}
