/*
* generated by Xtext
*/
package com.holycityaudio.spincad.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpinCADAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/holycityaudio/spincad/parser/antlr/internal/InternalSpinCAD.tokens");
	}
}
