/**
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu.validation;

import com.holycityaudio.spincadmenu.validation.AbstractSpinCADMenuValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SpinCADMenuValidator extends AbstractSpinCADMenuValidator {
}
