/*
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpinCADMenuUiModule extends com.holycityaudio.spincadmenu.ui.AbstractSpinCADMenuUiModule {
	public SpinCADMenuUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
