/*
* generated by Xtext
*/
package com.holycityaudio.spincadmenu.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpinCADMenuAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/holycityaudio/spincadmenu/parser/antlr/internal/InternalSpinCADMenu.tokens");
	}
}
