/*
* generated by Xtext
*/
package com.holycityaudio.spincad;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SpinCADUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.holycityaudio.spincad.ui.internal.SpinCADActivator.getInstance().getInjector("com.holycityaudio.spincad.SpinCAD");
	}
	
}
