/*
* generated by Xtext
*/
package com.holycityaudio.spincadmenu;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SpinCADMenuStandaloneSetup extends SpinCADMenuStandaloneSetupGenerated{

	public static void doSetup() {
		new SpinCADMenuStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

