/*
 * generated by Xtext
 */
package com.holycityaudio.spincad.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SpinCADUiModule extends com.holycityaudio.spincad.ui.AbstractSpinCADUiModule {
	public SpinCADUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
