/*
 * generated by Xtext
 */
package com.holycityaudio.spincad;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpinCADRuntimeModule extends com.holycityaudio.spincad.AbstractSpinCADRuntimeModule {

}
