/**
 * generated by Xtext
 */
package com.holycityaudio.spincad.ui.contentassist;

import com.holycityaudio.spincad.ui.contentassist.AbstractSpinCADProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SpinCADProposalProvider extends AbstractSpinCADProposalProvider {
}
