/*
 * generated by Xtext
 */
package com.holycityaudio.spincadmenu;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SpinCADMenuRuntimeModule extends com.holycityaudio.spincadmenu.AbstractSpinCADMenuRuntimeModule {

}
