/**
 * generated by Xtext
 */
package com.holycityaudio.spincad.validation;

import com.holycityaudio.spincad.validation.AbstractSpinCADValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SpinCADValidator extends AbstractSpinCADValidator {
}
