/*
 * generated by Xtext
 */
package com.holycityaudio.spincad.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.holycityaudio.spincad.ui.internal.SpinCADActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpinCADExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SpinCADActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SpinCADActivator.getInstance().getInjector(SpinCADActivator.COM_HOLYCITYAUDIO_SPINCAD_SPINCAD);
	}
	
}
